Chore/update typescript (#2106)
* Add vue-tsc

* Fix easy types

* Ignore type

* Remove mixins

* Fix input events

* Stub react types

* Fix GaugeVoteModal.vue types

* Fix some errors

* Fix userUserStakingData.ts

* Fix BalTable.vue

* Update ts and vue

* Update vue-slider-component, it contained global shim for JSX

* Use older version of ts for now

* Fix useInputEvents

* Fix choose weights

* fix create and InitialLiquidity

* Fix staking types

* Fix: Type 'Partial<PoolToken>[]' is not assignable to type 'PoolToken[]'.

* UnstakedPoolsTable.vue:77:16 - error TS2532: Object is possibly 'undefined'.

* UnstakedPoolsTable.vue:149:8 - error TS2322: Type 'Pool | undefined' is not assignable to type 'AnyPool'. Type 'undefined' is not assignable to type 'AnyPool'.

* UnstakedPoolsTable.vue:139:10 - error TS2322: Type 'PoolWithShares[]' is not assignable to type 'string | number | symbol | undefined'.

* MyVeBalCards.vue:207:8 - error TS2322: Type 'BigNumber' is not assignable to type 'string'.

* MyVeBalCards.vue:207:8 - error TS2322: Type 'BigNumber' is not assignable to type 'string'.

* WithdrawActions.vue:234:31 - error TS2322: Type '{ to: string; from: string; contractAddress: string; transactionIndex: number; root?: string | undefined; gasUsed: { readonly _hex: string; readonly _isBigNumber: boolean; fromTwos: (value: number) => BigNumber; ... 25 more ...; toJSON: (key?: string | undefined) => any; }; ... 10 more ...; status?: number | undefin...' is not assignable to type 'TransactionReceipt'.
  Type 'undefined' is not assignable to type 'TransactionReceipt'.

* LMVoting.vue:188:8 - error TS2322: Type 'Ref<undefined> | Ref<VeBalLockInfo>' is not assignable to type 'VeBalLockInfo | undefined'.
  Type 'Ref<undefined>' is missing the following properties from type 'VeBalLockInfo': lockedEndDate, lockedAmount, totalSupply, epoch, and 2 more.

* InvestActions.vue:219:31 - error TS2322: Type '{ to: string; from: string; contractAddress: string; transactionIndex: number; root?: string | undefined; gasUsed: { readonly _hex: string; readonly _isBigNumber: boolean; fromTwos: (value: number) => BigNumber; ... 25 more ...; toJSON: (key?: string | undefined) => any; }; ... 10 more ...; status?: number | undefin...' is not assignable to type 'TransactionReceipt'.
  Type 'undefined' is not assignable to type 'TransactionReceipt'.

* VeBalForm.vue:174:8 - error TS2322: Type 'VeBalLockInfo | undefined' is not assignable to type 'VeBalLockInfo'.
  Type 'undefined' is not assignable to type 'VeBalLockInfo'.

* Downgrading vue made trading page and staking accordion work again

* TokenSelectInput.vue:136:33 - error TS2339: Property 'optionToken' does not exist on type

* BalTable.vue:329:19 - error TS2722: Cannot invoke an object which is possibly 'undefined'.

* PoolTransferLayout.vue:92:37 - error TS2322: Type 'Pool | undefined' is not assignable to type 'Pool'.
  Type 'undefined' is not assignable to type 'Pool'.

* BoostedPool.vue:118:16 - error TS2322: Type 'string | null' is not assignable to type 'string'.
  Type 'null' is not assignable to type 'string'.

* LockForm.vue:95:12 - error TS2322: Type 'TokenInfo | null' is not assignable to type 'TokenInfo'.
  Type 'null' is not assignable to type 'TokenInfo'.

* APRTooltip.vue:93:12 - error TS2322: Type 'PoolType' is not assignable to type 'PoolType'.

* MigrateForm.vue:86:8 - error TS2322: Type 'Pool | undefined' is not assignable to type 'Pool'.
  Type 'undefined' is not assignable to type 'Pool'.

* FaucetTable.vue:87:19 - error TS2339: Property 'isLoading' does not exist on type '{ $: ComponentInternalInstance; : {}; : Partial<{}> & Omit<Readonly<{} & {} & {}> & VNodeProps & AllowedComponentProps & ComponentCustomProps, never>; ... 10 more ...; (source: string | Function, cb: Function, options?: WatchOptions<...> | undefined): WatchStopHandle; } & ... 4 more ... & ComponentC...'.

* portfolio.vue:57:18 - error TS2322: Type 'PoolWithShares[]' is not assignable to type 'string | number | symbol | undefined'.

* invest.vue:57:20 - error TS2322: Type 'Pool | undefined' is not assignable to type 'Pool'.
  Type 'undefined' is not assignable to type 'Pool'.

* PoolTransferLayout.vue:47:12 - error TS2322: Type 'Pool | undefined' is not assignable to type 'Pool'.
  Type 'undefined' is not assignable to type 'Pool'.

* StakedPoolsTable.vue:67:10 - error TS2322:  :key=poolsWithBoost
  node_modules/@vue/runtime-dom/dist/runtime-dom.d.ts: 1478   key?: string | number | symbol

* TokenAmounts.vue:54:35 - error TS2345: Argument of type 'string | number' is not assignable to parameter of type 'string'.
  Type 'number' is not assignable to type 'string'.

* DesktopLinks.vue:8:1 - error TS1232: An import declaration can only be used in a namespace or module.

* DripBtn.vue:39:5 - error TS2322: Type 'drip' is not assignable to type 'TransactionAction'.

* BalClaimsTable.vue:17:10 - error TS2614: Module '@/pages/claim.vue' has no exported member 'GaugePool'. Did you mean to use 'import GaugePool from @/pages/claim.vue' instead?

* BalTextInput.vue:26:1 - error TS1184: Modifiers cannot appear here.

* Add the types file

* VeBalPoolTable.vue:55:10 - error TS2322: Type 'PoolWithShares[]' is not assignable to type 'string | number | symbol | undefined'.
  Type 'PoolWithShares[]' is not assignable to type 'string'

* Remove console log

* Fix pool creating page

* Remove @vue/compiler-sfc, it's part of vue core now

* VeBalUnlockForm.vue:109:8 - error TS2322: Type 'BigNumber' is not assignable to type 'string'.

* UnlockForm.vue:67:8 - error TS2322: Type 'TokenInfo | null' is not assignable to type 'TokenInfo'.
  Type 'null' is not assignable to type 'TokenInfo'.

* UnlockActions.vue:134:18 - error TS2339: Property 'disabled' does not exist on type '{ $: ComponentIn

* UnlockAmount.vue:69:47 - error TS2339: Property 'tokenAddresses' does not exist on type 'Pool'.

* LockAmount.vue:49:8 - error TS2322: Type 'BigNumber' is not assignable to type 'string'.

* withdraw.vue:32:22 - error TS2322: Type 'Pool | undefined' is not assignable to type 'Pool'.
  Type 'undefined' is not assignable to type 'Pool'.

* portfolio.vue:45:14 - error TS2322: Type 'VeBalLockInfo | undefined' is not assignable to type 'VeBalLockInfo'.
  Type 'undefined' is not assignable to type 'VeBalLockInfo'.

* Add typecheck to Test job

* Script to generate global component types

* Remove quiet flag

* App.vue:131:50 - error TS2554: Expected 1 arguments, but got 2.

* TradeRoute.vue:93:39 - error TS2339: Property 'hops' does not exist on type 'never'.

* _id.vue:265:16 - error TS2322: Type 'Pool | undefined' is not assignable to type 'Pool'.
  Type 'undefined' is not assignable to type 'Pool'.

* _id.vue:224:16 - error TS2322: Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.

* TradePreviewModalGP.vue:407:8 - error TS2322: Type '({ id: string; swapFee: { readonly c: number[] | null; readonly e: number | null; readonly s: number | null; absoluteValue: () => BigNumber; abs: () => BigNumber; comparedTo: (n: Value, base?: number | undefined) => number; ... 45 more ...; valueOf: () => string; }; totalWeight: { ...; }; tokens: { ...; }[]; tokensL...' is not assignable to type '(Pool | SubgraphPoolBase)[]'.

407       :pools=trading.sor.pools.value

* ActivityRows.vue:59:38 - error TS2345: Argument of type 'string' is not assignable to parameter of type 'Transaction'

* TradeCard.vue:54:10 - error TS2322: Type '({ id: string; swapFee: { readonly c: number[] | null; readonly e: number | null; readonly s: number | null; absoluteValue: () => BigNumber; abs: () => BigNumber; comparedTo: (n: Value, base?: number | undefined) => number; ... 45 more ...; valueOf: () => string; }; totalWeight: { ...; }; tokens: { ...; }[]; tokensL...' is not assignable to type '(Pool | SubgraphPoolBase)[]'.

* AppNavAccountBtn.vue:18:12 - error TS2322: Type 'string | null | undefined' is not assignable to type 'string | undefined'.
  Type 'null' is not assignable to type 'string | undefined'.

* WalletSelectModal.vue:19:16 - error TS2322: Type 'Function' is not assignable to type '(payload: MouseEvent) => void'.
  Type 'Function' provides no match for the signature '(payload: MouseEvent): void'.

* AppNavNetworkSelect.vue:11:14 - error TS2532: Object is possibly 'undefined'.

* Update comment

* Update typescript

* BalInlineInput.vue:148:14 - error TS2322: Type '(e: HtmlInputEvent) => void' is not assignable to type '(payload: FocusEvent) => void'.

* BalInlineInput.vue:26:1 - error TS1184: Modifiers cannot appear here.

* Fix BalImage typings

* Use ts for BalRangeInput

* Use ts 4.4.4

* Add global component types

* PoolChart.vue:410:8 - error TS2322: Type '{ name: string; values: (readonly (string | number)[])[]; }[]' is not assignable to type 'ChartData[]'.

* PairPriceGraph.vue:326:17 - error TS2322: Type '{ 'flex-row': boolean; 'flex-col': boolean | undefined; }' is not assignable to type 'string'.
PairPriceGraph.vue:323:38 - error TS2322: Type 'string' is not assignable to type 'FNumOptions | undefined'.

* PreviewPool.vue:286:16 - error TS2322
BalInlineInput.vue:28:3
    28   name: string;
         ~~~~
    'name' is declared here.

* BalChart.vue:362:25 - error TS2345: Argument of type 'readonly [string, number]' is not assignable to parameter of type 'string | number'.

* Remove console log

* src/pages/pool/create.vue:374:12 - error TS2739: Type 'string[]' is missing the following properties from type 'Ref<unknown>': value, [RefSymbol]

* InvestForm.vue:268:18 - error TS2322: Type '(v: any) => string | true' is not assignable to type 'RuleFunction'.
  Type 'string | true' is not assignable to type 'string'.
    Type 'boolean' is not assignable to type 'string'

* PoolsTable.vue:259:9 - error TS2322: Type '{ to: string; getParams: (pool: any) => { id: any; }; }' is not assignable to type '{ to?: string | undefined; }'.
  Object literal may only specify known properties, and 'getParams' does not exist in type '{ to?: string | undefined; }'.

* TokenInput.vue:221:4 - error TS2322: Property 'name' is missing in type BalTextInput

* TokenAmounts.vue:44:20 - error TS2322: Type 'string | number' is not assignable to type 'string | undefined'.

* DefaultPool.vue:9:8 - error TS2322: Type 'string' is not assignable to type 'left | right | center | undefined'.

* Table.vue:6:10 - error TS2614: Module '@/components/_global/BalTable/BalTable.vue' has no exported member 'ColumnDefinition'. Did you mean to use 'import ColumnDefinition from @/components/_global/BalTable/BalTable.vue' instead?

* Fix imports

* GaugesTable.vue:180:8 - error TS2322: Type 'VotingGaugeWithVotes[]' is not assignable to type 'string | number | symbol | undefined'.
  Type 'VotingGaugeWithVotes[]' is not assignable to type 'string'.

* TxActionBtn.vue:115:6 - error TS2322: Type 'unknown' is not assignable to type 'boolean | undefined'.
  Type 'unknown' is not assignable to type 'true'.

* /ProportionalWithdrawalInput.vue:159:24 - error TS2322: Type 'string | number' is not assignable to type 'string | undefined'.
  Type 'number' is not assignable to type 'string | undefined'.

* Update ts

* Generate global component types

* Downgrade vue to fix balaccordion component

* Ignore pool type error

* Import Rule types

* Clean up HtmlInputEvent

* Move react shim file

* Cleanup1

* Use default null prop

* Cleanup2

* Cleanup3

* Use Record object types

* Type fixes

* Use fiat currency style for PairPriceGraph label

* Use unknown type for wrapperClasses

* Add description to global-component-types.generator

* Set veBalLockInfo prop as optional

* Remove typecheck from build script, types checked only in "Test" CI job

* Use script setup for pool page

* Use script setup for trade modal