FaucetTable.vue:87:19 - error TS2339: Property 'isLoading' does not exist on type '{ $: ComponentInternalInstance; : {}; : Partial<{}> & Omit<Readonly<{} & {} & {}> & VNodeProps & AllowedComponentProps & ComponentCustomProps, never>; ... 10 more ...; (source: string | Function, cb: Function, options?: WatchOptions<...> | undefined): WatchStopHandle; } & ... 4 more ... & ComponentC...'.