PoolsTable.vue:259:9 - error TS2322: Type '{ to: string; getParams: (pool: any) => { id: any; }; }' is not assignable to type '{ to?: string | undefined; }'.   Object literal may only specify known properties, and 'getParams' does not exist in type '{ to?: string | undefined; }'.