LMVoting.vue:188:8 - error TS2322: Type 'Ref<undefined> | Ref<VeBalLockInfo>' is not assignable to type 'VeBalLockInfo | undefined'.   Type 'Ref<undefined>' is missing the following properties from type 'VeBalLockInfo': lockedEndDate, lockedAmount, totalSupply, epoch, and 2 more.